language: go
go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - master

sudo: false

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get
  - go build

script:
  - make test
  - go test -coverprofile=cover.out github.com/tencentyun/cos-go-sdk-v5
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=cover.out

matrix:
  allow_failures:
    - go: 1.6
    - go: 1.7
    - go: master
